<html>
    <head>
        <title><?= isset($title) ? $title : "" ?></title>
        <link rel="stylesheet" href="<?= $this->asset("public/css/spectre.min.css"); ?>">
        <link rel="stylesheet" href="<?= $this->asset("public/css/layout.css"); ?>">
    </head>
    <body>
       
        <div class="container"> 
            <header class="navbar">
                <section class="navbar-section">
                    <a href="<?= $this->url("home") ?>" class="navbar-brand mr-2"><img src="<?= $this->asset("public/images/logo.png"); ?>"/> EU Transparency Register</a>
                </section>
                <section class="navbar-section">
                  <a href="#" class="btn btn-link">Test</a>
                  <a href="#" class="btn btn-link">Test</a>
                </section>
             </header>
        </div>
        <div class="container">     
            <?=$this->section('content')?>
        </div>
    </body>
</html>